Repository alexa/alexa-skills-kit-sdk-for-nodejs, pull requests merged in 2018-05, with the labels that each got.

#389 fix: update execution behavior of interceptor
  ask-sdk-core/lib/dispatcher/DefaultRequestDispatcher.ts
  ask-sdk-core/lib/skill/Skill.ts
  ask-sdk-core/lib/skill/SkillConfiguration.ts
  ask-sdk-core/lib/skill/factory/BaseSkillFactory.ts
  ask-sdk-core/tst/dispatcher/DefaultRequestDispatcher.spec.ts
Labels: 2.x.x

#299 Fix Readme.md to fix grammar
  Readme.md
Labels: 1.x.x, documentation, needs review

#371 bug fix: correctly refer to the handlers dynamo db client
  lib/response.js
Labels: 1.x.x, needs review

#229 npm test command runnable
  package.json
Labels: 1.x.x, response needed
